#一般リポジトリ用ビルドテスト
name: API Test

on:
  push:
    branches-ignore:
      - release/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules(package-lock.json)
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.OS }}-build-${{ env.cache-name }}-
      - name: Install node modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          rm package-lock.json
          npm install
      - name: Build
        run: npm run build:all
      - name: API test
        run: npm run test
