name: GitHub BuildTest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: BuildTest
        run: |
          yarn install
          yarn build:all
