#masterリポジトリ用デプロイ設定
name: Deploy master
on:
  push:
    branches:
      - release/*

jobs:
  build:
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: xbrowser-yarn-${{ hashFiles('**\package-lock.json') }}
          restore-keys: |
            xbrowser-yarn-
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: |
          npm run build:all
      - name: API test
        run: npm run test
      - name: Deploy
        run: |
          bash .github/scripts/deploy.sh
